### ISSUE TITLE
lanuages_list does not work

### ISSUE THREAD

**Issue by rschweigert** [amnemonic/dokuprism#1]
Nice Plugin! But: tried to configure languages_list, first in Dokuwiki Configurationmanager and then in ~/dokuwiki/lib/plugins/dokuprism/conf/default.php. Both attempts failed. It's probably caused by the quite old dokuwiki-version (2017-02-19b "Frusterick Manners" with php5.6.4) that I am using.

**Comment by amnemonic** [comment]
Thank you for feedback. Unfortunately ocasionally I experienced same issue on 2018-04-22b "Greebo" and also on devel snapshot. Current workaround for this issue is calling page:
`http://www.example.com/lib/exe/js.php?purge=true`
as stated on https://www.dokuwiki.org/devel:caching. I don't know yet if it is general DokuWiki issue or plugin problem. Please try mentioned link and let us know if it helped.

**Comment by rschweigert** [comment]
Thanks for your replay. Your suggestion did the job!
Regards

Am Samstag, 22. Februar 2020, 13:12:34 CET schrieb Adam Mnemonic:
> Thank you for feedback. Unfortunately ocasionally I experienced same issue
> on 2018-04-22b "Greebo" and also on devel snapshot. Current workaround for
> this issue is calling page:
> `http://www.example.com/lib/exe/js.php?purge=true`
> as stated on https://www.dokuwiki.org/devel:caching. I don't know yet if it
> is general DokuWiki issue or plugin problem. Please try mentioned link and
> let us know if it helped.
